version: '3.9'


services:
  dev-rabbitmq:
    image: rabbitmq:3.9.22-management-alpine
    container_name: yuvod-rabbitmq-poc
    restart: always
    tty: true
    stdin_open: true
    hostname: yuvod-rabbitmq-poc
    ports:
      # HTTP Dashboard
      - "15675:15672"
      # AMQP
      - "5679:5672"
    environment:
      RABBITMQ_DEFAULT_USER: yuvod
      RABBITMQ_DEFAULT_PASS: pass

  